### ISSUE TITLE
SigningError: Missing credentials in config

### ISSUE THREAD

**Issue by Allakonda** [extrabacon/dynamodb-model#7]
> I have already configured AWS_PROFILE to claudia and added the credentials. It's working fine with dynamodb but not with dynamodb-model and have tried every possibility to workout with the AWS credentials its working fine for everything except "dynamodb-model"

## This is the code
```
var DynamoDBModel = require('dynamodb-model');

var demoSchema = new DynamoDBModel.Schema({
	userId: {
		type: Number,
	},
	name: {
		type: String
	},
	age: {
		type: Number
	}
});

var demoTable = new DynamoDBModel.Model('demo', demoSchema);
let data = {
	"userId":5,
	"name": "SomeX",
	"age":22
};
demoTable.putItem(data, function(err, response){
	if(err){
		console.log('Outside demoTable error', err);
	}else{
		console.log(response);
	}
});
```

## And the error is

```
Outside demoTable error { SigningError: Missing credentials in config
    at ClientRequest.<anonymous> (/tmp/513834b7-304b-4ab0-a4e3-6f95e45c0c6e/node_modules/dynamodb-model/node_modules/aws-sdk/lib/http.js:204:34)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:629:10)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14) code: 'SigningError', name: 'SigningError' }
```

**Comment by steckdev** [comment]
I have the same issue!

**Comment by chiragkalani** [comment]
I have the same issue!
